### ISSUE TITLE
data missing, not able to run sample

### ISSUE THREAD

**Issue by jeffyeh** [Azure/spark-cdm-connector#31]
Hi,

Tried to run the sample but not seeing following data/ files.
implicitTest
explicitTest
nestedImplicit
nestedExplicit

Wonder is there any dependency package before this to get running?

**Comment by sricheta92** [comment]
Hi @jeffyeh 
When you execute 
```df.write.format("com.microsoft.cdm")
  .option("storage", storageAccountName)
  .option("container", container)
  .option("manifest", "/implicitTest/default.manifest.cdm.json")
  .option("entity", "TestEntity")
  .option("format", "parquet")
  .option("compression", "gzip")
  .option("appId", appid)
  .option("appKey", appkey)
  .option("tenantId", tenantid)
  .mode(SaveMode.Append)
  .save()
```

the manifest  `default.manifest.cdm.json` will get created  on container `container` under ADLSgen2 account `storageAccountName`. So you don't need any dependency for implicitTest and nestedImplicit. However, you would need dependencies for explicit writes because it is based on a pre-defined model. The dependencies are located under samples/Contacts folder.

**Comment by jeffyeh** [comment]
Thanks for the reply. However I'm still not able to get it through from my local notebook. I'm using pyspark.

The spark-cdm-connector library is installed.
```
Pixiedust database opened successfully
Pixiedust version 1.1.18
Package already installed: com.microsoft.azure:spark-cdm-connector:0.14
com.microsoft.azure:spark-cdm-connector:0.14 => /Users/jeffyeh/pixiedust/data/libs/spark-cdm-connector-0.14.jar
```

However I'm still fail to find the format for "com.microsoft.cdm". 
```
Py4JJavaError: An error occurred while calling o59.save.
: java.lang.ClassNotFoundException: Failed to find data source: com.microsoft.cdm. Please find packages at http://spark.apache.org/third-party-projects.html
```
