### ISSUE TITLE
Parquet files written by the connector cannot be read by other parquet readers

### ISSUE THREAD

**Issue by Sandy247** [Azure/spark-cdm-connector#39]
When trying to read the files created by the connector into a pandas dataframe, fastparquet  gives:
**AttributeError: 'NoneType' object has no attribute 'definition_level_encoding'**,

while pyarrow gives:
**OSError: Not yet implemented: Unsupported encoding.**

Have tried with both uncompressed parquet files as well as snappy compressed. Reading through the connector works perfectly, though. Is this use case currently supported?

**Comment by sricheta92** [comment]
Hi @Sandy247 

Can you please share the CDM folder(including the manifest and data partitions) that were created by the connector?

Thanks,
Sricheta.

**Comment by Sandy247** [comment]
Hi @sricheta92 ,
PFA

[CDM Folder](https://ffcinc-my.sharepoint.com/:f:/g/personal/sarkar_skypointcloud_com/En30riBMEwJGkM5hRya2sTIBWInUxFpSo1iJngaCmCpveA?e=lZHxX8)

**Comment by sricheta92** [comment]
Thanks, Sayandip. May I know which version of the connector did you use to write the CDM folder?

**Comment by Sandy247** [comment]
Thanks for the workaround @sricheta92. I will try it out and let you know. Also, fyi, I am using version 0.16 of the spark-cdm-connector(the latest one, I believe) to write to the CDM folder.

**Comment by Sandy247** [comment]
Hey @sricheta92, any update on this?

**Comment by sricheta92** [comment]
Hey @Sandy247, As previously said the connector uses ParquetWriter v2 to write to the CDM folder. Please see https://issues.apache.org/jira/browse/ARROW-6057?src=confmacro and https://fastparquet.readthedocs.io/en/latest/#caveats-known-issues.  This says, clearly that pyarrow cannot read parquet files writer with v2 writer.  As per fastparquet   It says not all encodings are supported. We are working on using the ParquetWriter v1 for the connector since that is the default version and expecting that to ship it in 0.18 version.

**Comment by Sandy247** [comment]
Thanks @sricheta92 for the clarification and helping me out with this. Really appreciate it. Looking forward to 0.18 when this gets resolved!

**Comment by srichetar** [comment]
This issue has been fixed in 0.18.1. Please verify on 0.18.1.

**Comment by Sandy247** [comment]
Hi @srichetar,
I can confirm that this issue is fixed with the new release. Really appreciate your help. Thanks!
